project:
  type: book
  output-dir: docs

book:
  title: "Data-330-Book"
  author: "Jon McCurdy"
  date: "8/19/2025"
  chapters:
    - index.qmd
    - Lecture-1.qmd
    - Lecture-2.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    css: 
      - style.css
  pdf:
    documentclass: scrreprt

editor: visual

